tests(e2e): use artifacts to share web dist update

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,4 +1,4 @@
-name: build
+name: Run Tests, build and Release
 
 on:
   push:
@@ -72,9 +72,9 @@ jobs:
           name: web-dist
           path: web/dist
 
-      - name: Copy dist to shared location
-        run: |
-          mv web/dist $GITHUB_WORKSPACE/
+#      - name: Copy dist to shared location
+#        run: |
+#          mv web/dist $GITHUB_WORKSPACE/
 
       - name: Create web-dist artifact
         if: startsWith(github.ref, 'refs/tags/')
@@ -87,58 +87,58 @@ jobs:
           files: |
             dist/web-dist.tar.gz
 
-  test-integration:
-    strategy:
-      fail-fast: true
-      matrix:
-        db: [ pg, sqlite ]
-    name: Test db integration ${{ matrix.db }}
-    runs-on: ubuntu-latest
-    services:
-      test_postgres:
-        image: postgres:12.10
-        ports:
-          - "5437:5432"
-        env:
-          POSTGRES_USER: testdb
-          POSTGRES_PASSWORD: testdb
-          POSTGRES_DB: autobrr
-        options: --health-cmd pg_isready --health-interval 1s --health-timeout 5s --health-retries 60
-    env:
-      CGO_ENABLED: 0
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: Set up Go
-        uses: actions/setup-go@v5
-        with:
-          go-version: ${{ env.GO_VERSION }}
-          cache: true
-
-      - name: Create Profile environment
-        run:
-          |
-          printf '#!/usr/bin/env bash\nset -eu\nfor pkg in $(go list "$@"); do\n\tgo test -json -cpuprofile="profile/$(echo $pkg | tr / -).pprof" ${{ startsWith(matrix.os, 'ubuntu') && '-tags=integration ' || '' }}"$pkg"\ndone' | tee -a profile.sh;
-          chmod +x profile.sh;
-          mkdir profile;
-
-      - name: Test
-        run: go run gotest.tools/gotestsum@latest --junitfile unit-tests.xml --format pkgname --raw-command ./profile.sh -- ./...
-
-      - name: Upload pprof
-        uses: actions/upload-artifact@v4
-        with:
-          name: pprof-test-${{ matrix.os }}
-          path: profile
-
-      - name: Test Summary
-        uses: test-summary/action@v2
-        with:
-          paths: "unit-tests.xml"
-        if: always()
+#  test-integration:
+#    strategy:
+#      fail-fast: true
+#      matrix:
+#        db: [ pg, sqlite ]
+#    name: Test db integration ${{ matrix.db }}
+#    runs-on: ubuntu-latest
+#    services:
+#      test_postgres:
+#        image: postgres:12.10
+#        ports:
+#          - "5437:5432"
+#        env:
+#          POSTGRES_USER: testdb
+#          POSTGRES_PASSWORD: testdb
+#          POSTGRES_DB: autobrr
+#        options: --health-cmd pg_isready --health-interval 1s --health-timeout 5s --health-retries 60
+#    env:
+#      CGO_ENABLED: 0
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v4
+#        with:
+#          fetch-depth: 0
+#
+#      - name: Set up Go
+#        uses: actions/setup-go@v5
+#        with:
+#          go-version: ${{ env.GO_VERSION }}
+#          cache: true
+#
+#      - name: Create Profile environment
+#        run:
+#          |
+#          printf '#!/usr/bin/env bash\nset -eu\nfor pkg in $(go list "$@"); do\n\tgo test -json -cpuprofile="profile/$(echo $pkg | tr / -).pprof" ${{ startsWith(matrix.os, 'ubuntu') && '-tags=integration ' || '' }}"$pkg"\ndone' | tee -a profile.sh;
+#          chmod +x profile.sh;
+#          mkdir profile;
+#
+#      - name: Test
+#        run: go run gotest.tools/gotestsum@latest --junitfile unit-tests.xml --format pkgname --raw-command ./profile.sh -- ./...
+#
+#      - name: Upload pprof
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: pprof-test-${{ matrix.os }}
+#          path: profile
+#
+#      - name: Test Summary
+#        uses: test-summary/action@v2
+#        with:
+#          paths: "unit-tests.xml"
+#        if: always()
 
   test:
     name: Run Unit and Integration tests
@@ -301,17 +301,11 @@ jobs:
         with:
           fetch-depth: 0
 
-#      - name: Download web production build
-#        uses: actions/download-artifact@v4
-#        with:
-#          name: web-dist
-#          path: web/dist
-
-      - name: Copy web production build from shared dir
-        run: |
-          ls -lah $GITHUB_WORKSPACE/
-          ls -lah $GITHUB_WORKSPACE/dist
-          cp $GITHUB_WORKSPACE/dist web/dist
+      - name: Download web production build
+        uses: actions/download-artifact@v4
+        with:
+          name: web-dist
+          path: web/dist
 
       - name: Set up Go
         uses: actions/setup-go@v5
@@ -389,17 +383,11 @@ jobs:
         with:
           fetch-depth: 0
 
-#      - name: Download web production build
-#        uses: actions/download-artifact@v4
-#        with:
-#          name: web-dist
-#          path: web/dist
-
-      - name: Copy web production build from shared dir
-        run: |
-          ls -lah $GITHUB_WORKSPACE/
-          ls -lah $GITHUB_WORKSPACE/dist
-          cp $GITHUB_WORKSPACE/dist web/dist
+      - name: Download web production build
+        uses: actions/download-artifact@v4
+        with:
+          name: web-dist
+          path: web/dist
 
       - name: Set up Go
         uses: actions/setup-go@v5
@@ -520,18 +508,11 @@ jobs:
         with:
           fetch-depth: 0
 
-#      - name: Download web production build
-#        uses: actions/download-artifact@v4
-#        with:
-#          name: web-dist
-#          path: web/dist
-
-      - name: Copy web production build from shared dir
-        run: |
-          ls -lah $GITHUB_WORKSPACE/
-          ls -lah $GITHUB_WORKSPACE/dist
-          cp $GITHUB_WORKSPACE/dist web/dist
-          ls -lah web/dist/
+      - name: Download web production build
+        uses: actions/download-artifact@v4
+        with:
+          name: web-dist
+          path: web/dist
 
       - name: Download pprof profile
         uses: actions/download-artifact@v4
@@ -613,18 +594,11 @@ jobs:
         with:
           fetch-depth: 0
 
-#      - name: Download web production build
-#        uses: actions/download-artifact@v4
-#        with:
-#          name: web-dist
-#          path: web/dist
-
-      - name: Copy web production build from shared dir
-        run: |
-          ls -lah $GITHUB_WORKSPACE/
-          ls -lah $GITHUB_WORKSPACE/dist
-          cp $GITHUB_WORKSPACE/dist web/dist
-          ls -lah web/dist/
+      - name: Download web production build
+        uses: actions/download-artifact@v4
+        with:
+          name: web-dist
+          path: web/dist
 
       - name: Download pprof profile
         uses: actions/download-artifact@v4
